service: tts-aws-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  v1TTS:
    handler: src.services.v1_tts.handler.v1_tts_lambda
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2TTS:
    handler: src.services.v2_tts.handler.v2_tts_lambda
    events:
      - httpApi:
          path: /v2/tts
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: True

package:
  exclude:
    - ./**
  include:
    - src/**